[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MaxMitre/Redes_Neuronales_Scratch/blob/main/Semana2/Ejercicio_PreciosCasas.ipynb)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np

In [ ]:
# Solo para que al mostrarnos los arreglos no nos de los valores grandes en notación científica
np.set_printoptions(suppress=True)

In [ ]:
file = open("/content/drive/MyDrive/Curso-NN-de-Cero/semana2/precios_casas_2.csv")
numpy_array = np.loadtxt(file, delimiter=",", skiprows=1)

In [ ]:
# La primer columna es el area en pies cuadrados
# La segunda columna es el año de construcción
# La tercera columna es el precio de venta
numpy_array

array([[  8450.,   2003., 208500.],
       [  9600.,   1976., 181500.],
       [ 11250.,   2001., 223500.],
       ...,
       [  9042.,   1941., 266500.],
       [  9717.,   1950., 142125.],
       [  9937.,   1965., 147500.]])

In [ ]:
numpy_array.shape

(1460, 3)

In [ ]:
file2 = open("/content/drive/MyDrive/Curso-NN-de-Cero/semana2/precios_casas_3.csv")
numpy_array2 = np.loadtxt(file2, delimiter=",", skiprows=1)

In [ ]:
# La primer columna es el area en pies cuadrados del lote
# La segunda columna es el año de construcción
# La tercera columna es el area en pies cuadrados del garage
# La cuarta columna es el precio de venta
numpy_array2

array([[  8450.,   2003.,    548., 208500.],
       [  9600.,   1976.,    460., 181500.],
       [ 11250.,   2001.,    608., 223500.],
       ...,
       [  9042.,   1941.,    252., 266500.],
       [  9717.,   1950.,    240., 142125.],
       [  9937.,   1965.,    276., 147500.]])